### ISSUE TITLE
How to extract text from PDF pages?

### ISSUE THREAD

**Issue by mirkancal** [NicolaVerbeeck/dart_pdf_reader#10]
Thank you for the package, I was trying to extract pages as text but stuck.

Is it possible to add this in readme?

What I've tried so far:

```dart
Future<String> convertPdfToText(String path) async {
  final stream = ByteStream(File(path).readAsBytesSync());
  final doc = await PDFParser(stream).parse();
  final catalog = await doc.catalog;
  final pages = await catalog.getPages();
  final firstPage = pages.getPageAtIndex(0);
  PDFPageNode? node = firstPage;
  
  StringBuffer sb = StringBuffer(); 
  while (node != null) {
    final content = await node.contentStream;
    final text = await content?.read();
    if (text != null) {
      final c = utf8.decode(text);
      sb.write(c);
    }

    node = node.parent;
  }
  return sb.toString(); 
}
```

I thought calling .read on content stream will return page as bytes but I had format issues during decoding. Not sure if it's related to my pdf or it's not the intented way of use.

**Comment by NicolaVerbeeck** [comment]
This package was not designed to do extraction of text, it provides an interface to read PDF elements, sadly for you, text is not included as an element but rather as a part of a page's content stream (which is a text stream containing drawing commands, some of which will be text drawing commands).

When you call read on the content stream it should be decodable as utf8 (even ascii) and then you can parse this stream to find text drawing operations to extract the text. The structure of the page's drawing commands can be found in the specification (https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/pdfreference1.7old.pdf) under section 4.

For this library I currently do not find/see a need to provide this out of the box

**Comment by mirkancal** [comment]
Thanks for the clarification.

**Comment by chrisDK1977** [comment]
@mirkancal Have you found a way to parse the text using the dart_pdf_reader?
