### ISSUE TITLE
Extracting page number from outline

### ISSUE THREAD

**Issue by SlenPlayz** [NicolaVerbeeck/dart_pdf_reader#121]
Hi sorry I can't seem to figure out how to extract the page number from `PDFOutlineItem`. I see it exports a `title` but for the action it only exports the action type. How do I get the destination page number from the action?

Here's my current code:
```dart
Uint8List importedPdfFile = File(result.files.single.path!).readAsBytesSync();
ByteStream pdfStream = ByteStream(importedPdfFile);
PDFDocument pdfDoc = await PDFParser(pdfStream).parse();
PDFDocumentCatalog pdfCatalog = await pdfDoc.catalog;
List<PDFOutlineItem>? pdfOutline = await pdfCatalog.getOutlines();
pdfOutline?.forEach((x) {
     print(x.title);
     print(x.action);
});
```

**Comment by NicolaVerbeeck** [comment]
If the outline's action is a goto action you can cast it to `PDFOutlineGoToAction` which contains the destination field. See the PDF specification (eg: 1.7 specification section 8.2.1) on how to interpret this destination

**Comment by SlenPlayz** [comment]
Found it thank you!
