### ISSUE TITLE
Excuse me, i can't find all the streams in contentstream

### ISSUE THREAD

**Issue by taihangg** [NicolaVerbeeck/dart_pdf_reader#148]
I try to extract the image, and parse the format data, so I try to scan all elements, especially the streams.
but it always only get one stream.

```
	final stream = ByteStream(_pdfFileData!);
    final doc = await PDFParser(stream).parse();
    final catalog = await doc.catalog;
    PDFPages pages = await catalog.getPages();
    try {
      for (int i = 0;; i++) {
        PDFPageObjectNode page = pages.getPageAtIndex(0);
        PDFPageNode? node = page;
        while (null != node) {
          List<PDFStreamObject>? contentStreams = await node.contentStreams;
          if (null != contentStreams) {
            print(contentStreams.length); // always is 1
            for (int i = 0; i < contentStreams.length; i++) {
              PDFStreamObject content = contentStreams[i];
              print(content.length); // always is 86
            }
          }
          node=node.parent;
        }
      }
    } catch (err) {}
```

[test.pdf](https://github.com/user-attachments/files/17039856/test.pdf)

<img width="885" alt="1726641612720" src="https://github.com/user-attachments/assets/0f73f3d9-e483-446d-8b77-47c18699ee15">

Can you give me some suggestion?
Thank you!

**Comment by NicolaVerbeeck** [comment]
The page's content streams are the streams describing the contents of the page, there are many more streams to be found in a document which are referenced by other bits (including other streams).

There is no way in the library to get access to all streams within a document. You could try getting every valid index, reading it and checking to see if it is a stream
