### ISSUE TITLE
`getPages` is surprisingly slow

### ISSUE THREAD

**Issue by sma** [NicolaVerbeeck/dart_pdf_reader#25]
I'm using this library as a base to extract text from pages and it is surprisingly slow. 

To load a 2,8 MB PDF with 55 pages using this code
```dart
  final file = File('/Users/sma/Downloads/qps1-the-minoan-affair.pdf');
  final stream = FileStream(file.openSync());
  final parser = PDFParser(stream);
  final doc = await parser.parse();
  final catalog = await doc.catalog;
  final pages = await catalog.getPages();
```
it needs ~7 seconds on my Mac (3,8 GHz 8-Core Intel Core i7) and loading a 640+ pages PDF (104 MB) takes ~31 seconds until I get a `Extends on compressed stream not supported yet` exception.  A simpler 336 pages PDF (30 MB) takes ~9 seconds. Asking for the catalog is fast, so I think, the `getPages` call is the culprit.

**Comment by NicolaVerbeeck** [comment]
Can you try reading the file to bytes and using ByteStream instead? File stream is slow and unbuffered, which needs work but time...

**Comment by NicolaVerbeeck** [comment]
0.2.6 will add a buffer wrapper for file streams which greatly improves performance. See `BufferedRandomAccessStream`

**Comment by sma** [comment]
Using a `ByteStream` is nearly instant. Thanks. You might want to add a warning to the `FileStream` class comment.

**Comment by NicolaVerbeeck** [comment]
There always has been a warning on it in ;)

**Comment by sma** [comment]
Well, you're of course right, and I think, I even glanced at that comment. Perhaps something like "**Please note:** Because of missing buffering, the [ByteStream] is 10x faster than this implementation, and if memory allows, you should consider using that class." would have caught my eyes.
