### ISSUE TITLE
ParseException: Extends on compressed stream not supported yet

### ISSUE THREAD

**Issue by sma** [NicolaVerbeeck/dart_pdf_reader#29]
While parsing a PDF, I get the above exception in line 60 of `indirect_object_parser.dart`. 

My PDF contains an object `3376 0 obj` starting with `<</Extends 3375 0 R/Filter/FlateDecode/First 696/Length 741/N 72/Type/ObjStm>>stream` which seems to be the continuation of said object that looks like this `<</Filter/FlateDecode/First 979/Length 948/N 100/Type/ObjStm>>stream`.  Both objects are rather small and not references anywhere else in the PDF (so probably either only the in xref or in some compressed data stream). Glancing at the PDF standard I don't really know why this feature exists, but it seems to be an optimisation to keep the number of indirect objects inside the stream data small.

I don't know whether I need these objects at all so an `Exception` is a rather harsh way to mark a limitation of the parser. 

If I remove that exception, my code seems to work just fine, but because my PDF has 600+ pages, I'm not sure whether something is missing now ;-) Still, I'd prefer to get just a warning and have still a working parser.

**Comment by NicolaVerbeeck** [comment]
They denote compressed objects which are referenced somewhere when reading whatever you need, in which case they cannot be skipped as they form part of the xref table. I have never seen a PDF with extended compressed object tables so support for this was not built.

If you have an example PDF where this happens that you can share, I can build support for this

**Comment by sma** [comment]
> If you have an example PDF where this happens that you can share, I can build support for this
Right now, I only noticed it in files I cannot share but I'll keep looking.

**Comment by sma** [comment]
This [free but rather large PDF](https://www.drivethrurpg.com/product/322377/) contains object streams with `/Extends` declaration.

**Comment by NicolaVerbeeck** [comment]
Thanks, I will take a look and see if we can start supporting extends somehow

**Comment by NicolaVerbeeck** [comment]
Experimental support for this is in 0.4.0

**Comment by sma** [comment]
Thanks, seems to work – at least, no exception ;-)
