### ISSUE TITLE
Apple's own PDF icons cannot be parsed because they are non-conforming

### ISSUE THREAD

**Issue by sma** [NicolaVerbeeck/dart_pdf_reader#36]
While trying to load every PDF on my computer, I stumbled upon `Xcode-beta.app/Contents/SharedFrameworks/DeltaKit.framework/Resources/ArrowRight.pdf` which fails to parse. This is because the `xref` entries have only 19 bytes, not 20. The standard requires lines to end with either SP CR, SP LF, or CR LF but those PDF icon files only use a single LF as a line terminator. I'm unsure how do deal with such non-conforming files but I wanted to at least document it, as it took some time to analyze :)

**Comment by NicolaVerbeeck** [comment]
![](https://media.tenor.com/xNIwSnv8tzkAAAAd/sheldon-cooper-throw-papers.gif)
