### ISSUE TITLE
_AssertionError ('package:dart_pdf_reader/src/parser/pdf_object_parser.dart': Failed assertion: line 275 pos 12: 'endLine == 'endstream'': is not true.)

### ISSUE THREAD

**Issue by sma** [NicolaVerbeeck/dart_pdf_reader#37]
Using version 0.0.4, I get the above error on an PDF with uses no line end marker between `endstream` and `endobj` which seems to be OK according to the spec. According the the PDF's meta data it was created by Foxit Software's PDF Producer in 2006. All other PDFs I've seen so far seem to use a line end marker as the mandatory whitespace and not just a single space.

**Comment by NicolaVerbeeck** [comment]
Good catch, the assert is more for my sanity than anything useful. I will remove this check as we don't care about this at all
