### ISSUE TITLE
Pdf without DecodeParams

### ISSUE THREAD

**Issue by zagronitay** [NicolaVerbeeck/dart_pdf_reader#38]
Hi @NicolaVerbeeck 

I encountered a PDF file without decode parameters.

The line of code `final decodeParams = await resolver .resolve<PDFObject>(dictionary[const PDFName('DecodeParms')]);` in lib/src/model/pdf_types.dart at line 449 raises an error.

I was able to solve the issue by changing the read method to the following:
```
 final params = <PDFObject>[];
  final decodeParamsDictionary = dictionary[const PDFName('DecodeParms')];
  if (decodeParamsDictionary != null) {
    final decodeParams =
        await resolver.resolve<PDFObject>(decodeParamsDictionary);
    if (decodeParams is PDFArray) {
      for (final p in decodeParams) {
        params.add(p);
      }
    } else if (decodeParams != null) {
      params.add(decodeParams);
    }
  }
```
This change allows me to successfully retrieve the pages and outlines of the PDF file.

Is there anything else I should look out for before pushing a pull request?

Thanks

**Comment by NicolaVerbeeck** [comment]
Cmcan you try v 0.4.0 first to see if the error persists?

**Comment by zagronitay** [comment]
😌 True!

Thanks mate
