### ISSUE TITLE
Unsupported operation: _newZLibDeflateFilter

### ISSUE THREAD

**Issue by a7-ctech** [NicolaVerbeeck/dart_pdf_reader#48]
I know it is mentioned that Flutter Web is not supported, but most pdf_reading is done on Web ;)

Can we use the archive package instead of GZipCodec() or will that kill the speed ?

**Comment by NicolaVerbeeck** [comment]
Strong statement that most pdf reading is done on web. I will have to look into it, though I know that archive package has performance implications

**Comment by NicolaVerbeeck** [comment]
On io platforms the archive package will fall back to dart:io so performance is not impacted for non-web contexts

**Comment by NicolaVerbeeck** [comment]
Version 0.5.0 was published to pub.dev
