### ISSUE TITLE
Converting the text content to String

### ISSUE THREAD

**Issue by dagimg-dot** [NicolaVerbeeck/dart_pdf_reader#73]
How do I convert the PDFObjectNode to a string

**Comment by NicolaVerbeeck** [comment]
This library in itself does not support this use-case, and will not in the future.

You can use the library itself to implement such a feature yourself though. This entails parsing the page's content stream(s) to find all BT and ET operators, matching with font/mappings,...

**Comment by dagimg-dot** [comment]
Okay thank you for your quick response. I will try it myself

**Comment by bettdouglas** [comment]
@NicolaVerbeeck could you please show a minimal example of how to parse contents of a single page? It would be cool to make this feature available for use in pure dart projects either in this package or as extensions to this package.

**Comment by NicolaVerbeeck** [comment]
Given that I've never used this library itself to do context extraction, I would have to write a full implementation as an example. Which does not fit within my currently available time
